//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catch2TestAdapter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InfoStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfoStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Catch2TestAdapter.Resources.InfoStrings", typeof(InfoStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch2Adapter is disabled..
        /// </summary>
        internal static string DiscoveryDisabled {
            get {
                return ResourceManager.GetString("DiscoveryDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch2Adapter Dll discovery is disabled..
        /// </summary>
        internal static string DllDiscoveryDisabled {
            get {
                return ResourceManager.GetString("DllDiscoveryDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch2Adapter Exe discovery is disabled..
        /// </summary>
        internal static string ExeDiscoveryDisabled {
            get {
                return ResourceManager.GetString("ExeDiscoveryDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Catch2Adapter exe test discovery..
        /// </summary>
        internal static string FinishedDiscovery {
            get {
                return ResourceManager.GetString("FinishedDiscovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Catch2Adapter dll test discovery..
        /// </summary>
        internal static string FinishedDiscoveryDll {
            get {
                return ResourceManager.GetString("FinishedDiscoveryDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Catch2Adapter exe test execution..
        /// </summary>
        internal static string FinishedExecutor {
            get {
                return ResourceManager.GetString("FinishedExecutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Catch2Adapter dll test execution..
        /// </summary>
        internal static string FinishedExecutorDll {
            get {
                return ResourceManager.GetString("FinishedExecutorDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started Catch2Adapter exe test discovery....
        /// </summary>
        internal static string StartDiscovery {
            get {
                return ResourceManager.GetString("StartDiscovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started Catch2Adapter dll test discovery....
        /// </summary>
        internal static string StartDiscoveryDll {
            get {
                return ResourceManager.GetString("StartDiscoveryDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started Catch2Adapter exe test execution....
        /// </summary>
        internal static string StartExecutor {
            get {
                return ResourceManager.GetString("StartExecutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started Catch2Adapter dll test execution....
        /// </summary>
        internal static string StartExecutorDll {
            get {
                return ResourceManager.GetString("StartExecutorDll", resourceCulture);
            }
        }
    }
}
