//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UT_Catch2Interface.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UT_Catch2Interface.Resources.TestStrings", typeof(TestStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Expression success=&quot;false&quot; type=&quot;CHECK&quot; filename=&quot;d:\test\ut_tests01.cpp&quot; line=&quot;32&quot;&gt;
        ///        &lt;Original&gt;
        ///          x == y
        ///        &lt;/Original&gt;
        ///        &lt;Expanded&gt;
        ///          1 == 2
        ///        &lt;/Expanded&gt;
        ///      &lt;/Expression&gt;.
        /// </summary>
        internal static string XmlExpression01 {
            get {
                return ResourceManager.GetString("XmlExpression01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Failure filename=&quot;d:\test\ut_tests03.cpp&quot; line=&quot;50&quot;&gt;
        ///   Fail 01
        ///&lt;/Failure&gt;.
        /// </summary>
        internal static string XmlFailute01 {
            get {
                return ResourceManager.GetString("XmlFailute01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Info&gt;
        ///    Info 01
        ///&lt;/Info&gt;.
        /// </summary>
        internal static string XmlInfo01 {
            get {
                return ResourceManager.GetString("XmlInfo01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;OverallResult success=&quot;false&quot; durationInSeconds=&quot;0.012602&quot;/&gt;.
        /// </summary>
        internal static string XmlOverallResult01 {
            get {
                return ResourceManager.GetString("XmlOverallResult01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;OverallResult success=&quot;true&quot;/&gt;.
        /// </summary>
        internal static string XmlOverallResult02 {
            get {
                return ResourceManager.GetString("XmlOverallResult02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;OverallResult success=&quot;true&quot; durationInSeconds=&quot;0.073561&quot;&gt;
        ///    &lt;StdOut&gt;
        ///cout 01
        ///cout 02
        ///    &lt;/StdOut&gt;
        ///&lt;/OverallResult&gt;.
        /// </summary>
        internal static string XmlOverallResult03 {
            get {
                return ResourceManager.GetString("XmlOverallResult03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;OverallResult success=&quot;false&quot; durationInSeconds=&quot;0.064298&quot;&gt;
        ///    &lt;StdErr&gt;
        ///cerr 01
        ///cerr 02
        ///    &lt;/StdErr&gt;
        ///&lt;/OverallResult&gt;.
        /// </summary>
        internal static string XmlOverallResult04 {
            get {
                return ResourceManager.GetString("XmlOverallResult04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;OverallResult success=&quot;false&quot; durationInSeconds=&quot;0.123456&quot;&gt;
        ///    &lt;StdOut&gt;
        ///cout 01
        ///cout 02
        ///    &lt;/StdOut&gt;
        ///    &lt;StdErr&gt;
        ///cerr 01
        ///cerr 02
        ///    &lt;/StdErr&gt;
        ///&lt;/OverallResult&gt;.
        /// </summary>
        internal static string XmlOverallResult05 {
            get {
                return ResourceManager.GetString("XmlOverallResult05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;OverallResults successes=&quot;42&quot; failures=&quot;6&quot; expectedFailures=&quot;5&quot; durationInSeconds=&quot;0.042105&quot;/&gt;.
        /// </summary>
        internal static string XmlOverallResults01 {
            get {
                return ResourceManager.GetString("XmlOverallResults01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;OverallResults successes=&quot;5&quot; failures=&quot;66&quot;/&gt;.
        /// </summary>
        internal static string XmlOverallResults02 {
            get {
                return ResourceManager.GetString("XmlOverallResults02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Section name=&quot;Only Section&quot; filename=&quot;d:\test\ut_tests01.cpp&quot; line=&quot;39&quot;&gt;
        ///  &lt;Expression success=&quot;false&quot; type=&quot;CHECK&quot; filename=&quot;d:\test\ut_tests01.cpp&quot; line=&quot;41&quot;&gt;
        ///    &lt;Original&gt;
        ///      x == y
        ///    &lt;/Original&gt;
        ///    &lt;Expanded&gt;
        ///      3 == 4
        ///    &lt;/Expanded&gt;
        ///  &lt;/Expression&gt;
        ///  &lt;OverallResults successes=&quot;0&quot; failures=&quot;1&quot; expectedFailures=&quot;0&quot; durationInSeconds=&quot;0.008798&quot;/&gt;
        ///&lt;/Section&gt;.
        /// </summary>
        internal static string XmlSection01 {
            get {
                return ResourceManager.GetString("XmlSection01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;DebugBreak&gt;&lt;/DebugBreak&gt;
        ///  &lt;DiscoverCommandLine&gt;&lt;/DiscoverCommandLine&gt;
        ///  &lt;DiscoverTimeout&gt;&lt;/DiscoverTimeout&gt;
        ///  &lt;FilenameFilter&gt;&lt;/FilenameFilter&gt;
        ///  &lt;IncludeHidden&gt;&lt;/IncludeHidden&gt;
        ///  &lt;Logging&gt;&lt;/Logging&gt;
        ///  &lt;StackTraceFormat&gt;&lt;/StackTraceFormat&gt;
        ///  &lt;StackTracePointReplacement&gt;&lt;/StackTracePointReplacement&gt;
        ///  &lt;TestCaseTimeout&gt;&lt;/TestCaseTimeout&gt;&lt;!-- Milliseconds --&gt;
        ///&lt;/Catch2Adapter&gt;.
        /// </summary>
        internal static string XmlSettings_AllEmptyElements {
            get {
                return ResourceManager.GetString("XmlSettings_AllEmptyElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;DebugBreak&gt;off&lt;/DebugBreak&gt;
        ///&lt;/Catch2Adapter&gt;.
        /// </summary>
        internal static string XmlSettings_DebugBreak_Off {
            get {
                return ResourceManager.GetString("XmlSettings_DebugBreak_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;DebugBreak&gt;on&lt;/DebugBreak&gt;
        ///&lt;/Catch2Adapter&gt;.
        /// </summary>
        internal static string XmlSettings_DebugBreak_On {
            get {
                return ResourceManager.GetString("XmlSettings_DebugBreak_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter disabled=&quot;true&quot;/&gt;.
        /// </summary>
        internal static string XmlSettings_Disabled_Minimal {
            get {
                return ResourceManager.GetString("XmlSettings_Disabled_Minimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;DiscoverCommandLine&gt;--discover&lt;/DiscoverCommandLine&gt;
        ///&lt;/Catch2Adapter&gt;.
        /// </summary>
        internal static string XmlSettings_DiscoverCommandLine {
            get {
                return ResourceManager.GetString("XmlSettings_DiscoverCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;DiscoverTimeout&gt;2000&lt;/DiscoverTimeout&gt;
        ///&lt;/Catch2Adapter&gt;.
        /// </summary>
        internal static string XmlSettings_DiscoverTimeout {
            get {
                return ResourceManager.GetString("XmlSettings_DiscoverTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///&lt;/Catch2Adapter&gt;.
        /// </summary>
        internal static string XmlSettings_Empty {
            get {
                return ResourceManager.GetString("XmlSettings_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter/&gt;.
        /// </summary>
        internal static string XmlSettings_EmptyElement {
            get {
                return ResourceManager.GetString("XmlSettings_EmptyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;FilenameFilter&gt;^Catch&lt;/FilenameFilter&gt;
        ///&lt;/Catch2Adapter&gt;.
        /// </summary>
        internal static string XmlSettings_FilenameFilter {
            get {
                return ResourceManager.GetString("XmlSettings_FilenameFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;DebugBreak&gt;on&lt;/DebugBreak&gt;
        ///  &lt;DiscoverCommandLine&gt;--discover&lt;/DiscoverCommandLine&gt;
        ///  &lt;DiscoverTimeout&gt;2000&lt;/DiscoverTimeout&gt;
        ///  &lt;FilenameFilter&gt;^Catch&lt;/FilenameFilter&gt;
        ///  &lt;IncludeHidden&gt;false&lt;/IncludeHidden&gt;
        ///  &lt;Logging&gt;Verbose&lt;/Logging&gt;
        ///  &lt;MessageFormat&gt;AdditionalInfo&lt;/MessageFormat&gt;
        ///  &lt;StackTraceFormat&gt;None&lt;/StackTraceFormat&gt;
        ///  &lt;StackTracePointReplacement&gt;_&lt;/StackTracePointReplacement&gt;
        ///  &lt;TestCaseTimeout&gt;20000&lt;/TestCaseTimeout&gt;&lt;!-- Milliseconds --&gt;
        ///&lt;/Catch2Adapter&gt;.
        /// </summary>
        internal static string XmlSettings_FullyCustom {
            get {
                return ResourceManager.GetString("XmlSettings_FullyCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter disabled=&quot;true&quot;&gt;
        ///  &lt;DebugBreak&gt;on&lt;/DebugBreak&gt;
        ///  &lt;DiscoverCommandLine&gt;--discover&lt;/DiscoverCommandLine&gt;
        ///  &lt;DiscoverTimeout&gt;2000&lt;/DiscoverTimeout&gt;
        ///  &lt;FilenameFilter&gt;^Catch&lt;/FilenameFilter&gt;
        ///  &lt;IncludeHidden&gt;false&lt;/IncludeHidden&gt;
        ///  &lt;Logging&gt;Verbose&lt;/Logging&gt;
        ///  &lt;MessageFormat&gt;AdditionalInfo&lt;/MessageFormat&gt;
        ///  &lt;StackTraceFormat&gt;None&lt;/StackTraceFormat&gt;
        ///  &lt;StackTracePointReplacement&gt;_&lt;/StackTracePointReplacement&gt;
        ///  &lt;TestCaseTimeout&gt;20000&lt;/TestCaseTimeout&gt;&lt;!-- Milliseconds --&gt;
        ///&lt;/Catch2Adapte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlSettings_FullyCustom_Disabled {
            get {
                return ResourceManager.GetString("XmlSettings_FullyCustom_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter disabled=&quot;false&quot;&gt;
        ///  &lt;DebugBreak&gt;on&lt;/DebugBreak&gt;
        ///  &lt;DiscoverCommandLine&gt;--discover&lt;/DiscoverCommandLine&gt;
        ///  &lt;DiscoverTimeout&gt;2000&lt;/DiscoverTimeout&gt;
        ///  &lt;FilenameFilter&gt;^Catch&lt;/FilenameFilter&gt;
        ///  &lt;IncludeHidden&gt;false&lt;/IncludeHidden&gt;
        ///  &lt;Logging&gt;Verbose&lt;/Logging&gt;
        ///  &lt;MessageFormat&gt;AdditionalInfo&lt;/MessageFormat&gt;
        ///  &lt;StackTraceFormat&gt;None&lt;/StackTraceFormat&gt;
        ///  &lt;StackTracePointReplacement&gt;_&lt;/StackTracePointReplacement&gt;
        ///  &lt;TestCaseTimeout&gt;20000&lt;/TestCaseTimeout&gt;&lt;!-- Milliseconds --&gt;
        ///&lt;/Catch2Adapt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlSettings_FullyCustom_NotDisabled {
            get {
                return ResourceManager.GetString("XmlSettings_FullyCustom_NotDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;IncludeHidden&gt;false&lt;/IncludeHidden&gt;
        ///&lt;/Catch2Adapter&gt;.
        /// </summary>
        internal static string XmlSettings_IncludeHidden_False {
            get {
                return ResourceManager.GetString("XmlSettings_IncludeHidden_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;IncludeHidden&gt;true&lt;/IncludeHidden&gt;
        ///&lt;/Catch2Adapter&gt;.
        /// </summary>
        internal static string XmlSettings_IncludeHidden_True {
            get {
                return ResourceManager.GetString("XmlSettings_IncludeHidden_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;Logging&gt;Debug&lt;/Logging&gt;
        ///&lt;/Catch2Adapter&gt;.
        /// </summary>
        internal static string XmlSettings_Logging_Debug {
            get {
                return ResourceManager.GetString("XmlSettings_Logging_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;Logging&gt;Normal&lt;/Logging&gt;
        ///&lt;/Catch2Adapter&gt;.
        /// </summary>
        internal static string XmlSettings_Logging_Normal {
            get {
                return ResourceManager.GetString("XmlSettings_Logging_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;Logging&gt;Quiet&lt;/Logging&gt;
        ///&lt;/Catch2Adapter&gt;.
        /// </summary>
        internal static string XmlSettings_Logging_Quiet {
            get {
                return ResourceManager.GetString("XmlSettings_Logging_Quiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;Logging&gt;Verbose&lt;/Logging&gt;
        ///&lt;/Catch2Adapter&gt;.
        /// </summary>
        internal static string XmlSettings_Logging_Verbose {
            get {
                return ResourceManager.GetString("XmlSettings_Logging_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        /// &lt;MessageFormat&gt;AdditionalInfo&lt;/MessageFormat&gt;
        ///&lt;/Catch2Adapter&gt;.
        /// </summary>
        internal static string XmlSettings_MessageFormat_AdditionalInfo {
            get {
                return ResourceManager.GetString("XmlSettings_MessageFormat_AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        /// &lt;MessageFormat&gt;None&lt;/MessageFormat&gt;
        ///&lt;/Catch2Adapter&gt;.
        /// </summary>
        internal static string XmlSettings_MessageFormat_None {
            get {
                return ResourceManager.GetString("XmlSettings_MessageFormat_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        /// &lt;MessageFormat&gt;StatsOnly&lt;/MessageFormat&gt;
        ///&lt;/Catch2Adapter&gt;.
        /// </summary>
        internal static string XmlSettings_MessageFormat_StatsOnly {
            get {
                return ResourceManager.GetString("XmlSettings_MessageFormat_StatsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        /// &lt;StackTraceFormat&gt;None&lt;/StackTraceFormat&gt;
        ///&lt;/Catch2Adapter&gt;.
        /// </summary>
        internal static string XmlSettings_StackTraceFormat_None {
            get {
                return ResourceManager.GetString("XmlSettings_StackTraceFormat_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        /// &lt;StackTraceFormat&gt;ShortInfo&lt;/StackTraceFormat&gt;
        ///&lt;/Catch2Adapter&gt;.
        /// </summary>
        internal static string XmlSettings_StackTraceFormat_ShortInfo {
            get {
                return ResourceManager.GetString("XmlSettings_StackTraceFormat_ShortInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter disabled=&quot;false&quot;&gt;
        ///  &lt;StackTracePointReplacement&gt;_&lt;/StackTracePointReplacement&gt;
        ///&lt;/Catch2Adapter&gt;.
        /// </summary>
        internal static string XmlSettings_StackTracePointReplacement {
            get {
                return ResourceManager.GetString("XmlSettings_StackTracePointReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;TestCaseTimeout&gt;20000&lt;/TestCaseTimeout&gt;&lt;!-- Milliseconds --&gt;
        ///&lt;/Catch2Adapter&gt;.
        /// </summary>
        internal static string XmlSettings_TestCaseTimeout {
            get {
                return ResourceManager.GetString("XmlSettings_TestCaseTimeout", resourceCulture);
            }
        }
    }
}
