//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UT_Catch2Interface.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestStrings_SettingsManager {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestStrings_SettingsManager() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UT_Catch2Interface.Resources.TestStrings_SettingsManager", typeof(TestStrings_SettingsManager).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;CombinedTimeout&gt;30000&lt;/CombinedTimeout&gt;&lt;!-- Milliseconds --&gt;
        ///  &lt;DebugBreak&gt;on&lt;/DebugBreak&gt;
        ///  &lt;DllFilenameFilter&gt;^CatchDll&lt;/DllFilenameFilter&gt;&quot;
        ///  &lt;DllPostfix&gt;_D&lt;/DllPostfix&gt;
        ///  &lt;DllRunner&gt;${dllpath}/CatchDllRunner.exe&lt;/DllRunner&gt;
        ///  &lt;DllRunnerCommandline&gt;${catch2} ${dll}&lt;/DllRunnerCommandline&gt;
        ///  &lt;DiscoverCommandLine&gt;--discover&lt;/DiscoverCommandLine&gt;
        ///  &lt;DiscoverTimeout&gt;2000&lt;/DiscoverTimeout&gt;
        ///  &lt;Environment&gt;
        ///    &lt;PATH&gt;D:\MyPath; D:\MyOtherPath&lt;/PATH&gt;
        ///    &lt;MyCustomEnvSetting value=&quot;de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlSettings_NoOverrides {
            get {
                return ResourceManager.GetString("XmlSettings_NoOverrides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;CombinedTimeout&gt;30000&lt;/CombinedTimeout&gt;&lt;!-- Milliseconds --&gt;
        ///  &lt;DebugBreak&gt;on&lt;/DebugBreak&gt;
        ///  &lt;DllFilenameFilter&gt;^CatchDll&lt;/DllFilenameFilter&gt;&quot;
        ///  &lt;DllPostfix&gt;_D&lt;/DllPostfix&gt;
        ///  &lt;DllRunner&gt;${dllpath}/CatchDllRunner.exe&lt;/DllRunner&gt;
        ///  &lt;DllRunnerCommandline&gt;${catch2} ${dll}&lt;/DllRunnerCommandline&gt;
        ///  &lt;DiscoverCommandLine&gt;--discover&lt;/DiscoverCommandLine&gt;
        ///  &lt;DiscoverTimeout&gt;2000&lt;/DiscoverTimeout&gt;
        ///  &lt;Environment&gt;
        ///    &lt;PATH&gt;D:\MyPath; D:\MyOtherPath&lt;/PATH&gt;
        ///    &lt;MyCustomEnvSetting value=&quot;de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlSettingsOverride_CombinedTimeout {
            get {
                return ResourceManager.GetString("XmlSettingsOverride_CombinedTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;CombinedTimeout&gt;30000&lt;/CombinedTimeout&gt;&lt;!-- Milliseconds --&gt;
        ///  &lt;DebugBreak&gt;on&lt;/DebugBreak&gt;
        ///  &lt;DllFilenameFilter&gt;^CatchDll&lt;/DllFilenameFilter&gt;&quot;
        ///  &lt;DllPostfix&gt;_D&lt;/DllPostfix&gt;
        ///  &lt;DllRunner&gt;${dllpath}/CatchDllRunner.exe&lt;/DllRunner&gt;
        ///  &lt;DllRunnerCommandline&gt;${catch2} ${dll}&lt;/DllRunnerCommandline&gt;
        ///  &lt;DiscoverCommandLine&gt;--discover&lt;/DiscoverCommandLine&gt;
        ///  &lt;DiscoverTimeout&gt;2000&lt;/DiscoverTimeout&gt;
        ///  &lt;Environment&gt;
        ///    &lt;PATH&gt;D:\MyPath; D:\MyOtherPath&lt;/PATH&gt;
        ///    &lt;MyCustomEnvSetting value=&quot;de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlSettingsOverride_DebugBreak {
            get {
                return ResourceManager.GetString("XmlSettingsOverride_DebugBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;CombinedTimeout&gt;30000&lt;/CombinedTimeout&gt;&lt;!-- Milliseconds --&gt;
        ///  &lt;DebugBreak&gt;on&lt;/DebugBreak&gt;
        ///  &lt;DllFilenameFilter&gt;^CatchDll&lt;/DllFilenameFilter&gt;
        ///  &lt;DllPostfix&gt;_D&lt;/DllPostfix&gt;
        ///  &lt;DllRunner&gt;${dllpath}/CatchDllRunner.exe&lt;/DllRunner&gt;
        ///  &lt;DllRunnerCommandline&gt;${catch2} ${dll}&lt;/DllRunnerCommandline&gt;
        ///  &lt;DiscoverCommandLine&gt;--discover&lt;/DiscoverCommandLine&gt;
        ///  &lt;DiscoverTimeout&gt;2000&lt;/DiscoverTimeout&gt;
        ///  &lt;Environment&gt;
        ///    &lt;PATH&gt;D:\MyPath; D:\MyOtherPath&lt;/PATH&gt;
        ///    &lt;MyCustomEnvSetting value=&quot;deb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlSettingsOverride_DiscoverCommandLine {
            get {
                return ResourceManager.GetString("XmlSettingsOverride_DiscoverCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;CombinedTimeout&gt;30000&lt;/CombinedTimeout&gt;&lt;!-- Milliseconds --&gt;
        ///  &lt;DebugBreak&gt;on&lt;/DebugBreak&gt;
        ///  &lt;DllFilenameFilter&gt;^CatchDll&lt;/DllFilenameFilter&gt;
        ///  &lt;DllPostfix&gt;_D&lt;/DllPostfix&gt;
        ///  &lt;DllRunner&gt;${dllpath}/CatchDllRunner.exe&lt;/DllRunner&gt;
        ///  &lt;DllRunnerCommandline&gt;${catch2} ${dll}&lt;/DllRunnerCommandline&gt;
        ///  &lt;DiscoverCommandLine&gt;--discover&lt;/DiscoverCommandLine&gt;
        ///  &lt;DiscoverTimeout&gt;2000&lt;/DiscoverTimeout&gt;
        ///  &lt;Environment&gt;
        ///    &lt;PATH&gt;D:\MyPath; D:\MyOtherPath&lt;/PATH&gt;
        ///    &lt;MyCustomEnvSetting value=&quot;deb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlSettingsOverride_DllPostfix {
            get {
                return ResourceManager.GetString("XmlSettingsOverride_DllPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;CombinedTimeout&gt;30000&lt;/CombinedTimeout&gt;&lt;!-- Milliseconds --&gt;
        ///  &lt;DebugBreak&gt;on&lt;/DebugBreak&gt;
        ///  &lt;DllFilenameFilter&gt;^CatchDll&lt;/DllFilenameFilter&gt;
        ///  &lt;DllPostfix&gt;_D&lt;/DllPostfix&gt;
        ///  &lt;DllRunner&gt;${dllpath}/CatchDllRunner.exe&lt;/DllRunner&gt;
        ///  &lt;DllRunnerCommandline&gt;${catch2} ${dll}&lt;/DllRunnerCommandline&gt;
        ///  &lt;DiscoverCommandLine&gt;--discover&lt;/DiscoverCommandLine&gt;
        ///  &lt;DiscoverTimeout&gt;2000&lt;/DiscoverTimeout&gt;
        ///  &lt;Environment&gt;
        ///    &lt;PATH&gt;D:\MyPath; D:\MyOtherPath&lt;/PATH&gt;
        ///    &lt;MyCustomEnvSetting value=&quot;deb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlSettingsOverride_DllRunner {
            get {
                return ResourceManager.GetString("XmlSettingsOverride_DllRunner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;CombinedTimeout&gt;30000&lt;/CombinedTimeout&gt;&lt;!-- Milliseconds --&gt;
        ///  &lt;DebugBreak&gt;on&lt;/DebugBreak&gt;
        ///  &lt;DllFilenameFilter&gt;^CatchDll&lt;/DllFilenameFilter&gt;
        ///  &lt;DllPostfix&gt;_D&lt;/DllPostfix&gt;
        ///  &lt;DllRunner&gt;${dllpath}/CatchDllRunner.exe&lt;/DllRunner&gt;
        ///  &lt;DllRunnerCommandline&gt;${catch2} ${dll}&lt;/DllRunnerCommandline&gt;
        ///  &lt;DiscoverCommandLine&gt;--discover&lt;/DiscoverCommandLine&gt;
        ///  &lt;DiscoverTimeout&gt;2000&lt;/DiscoverTimeout&gt;
        ///  &lt;Environment&gt;
        ///    &lt;PATH&gt;D:\MyPath; D:\MyOtherPath&lt;/PATH&gt;
        ///    &lt;MyCustomEnvSetting value=&quot;deb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlSettingsOverride_Environment {
            get {
                return ResourceManager.GetString("XmlSettingsOverride_Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;CombinedTimeout&gt;30000&lt;/CombinedTimeout&gt;&lt;!-- Milliseconds --&gt;
        ///  &lt;DebugBreak&gt;on&lt;/DebugBreak&gt;
        ///  &lt;DllFilenameFilter&gt;^CatchDll&lt;/DllFilenameFilter&gt;
        ///  &lt;DllPostfix&gt;_D&lt;/DllPostfix&gt;
        ///  &lt;DllRunner&gt;${dllpath}/CatchDllRunner.exe&lt;/DllRunner&gt;
        ///  &lt;DllRunnerCommandline&gt;${catch2} ${dll}&lt;/DllRunnerCommandline&gt;
        ///  &lt;DiscoverCommandLine&gt;--discover&lt;/DiscoverCommandLine&gt;
        ///  &lt;DiscoverTimeout&gt;2000&lt;/DiscoverTimeout&gt;
        ///  &lt;Environment&gt;
        ///    &lt;PATH&gt;D:\MyPath; D:\MyOtherPath&lt;/PATH&gt;
        ///    &lt;MyCustomEnvSetting value=&quot;deb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlSettingsOverride_ExecutionMode {
            get {
                return ResourceManager.GetString("XmlSettingsOverride_ExecutionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;CombinedTimeout&gt;30000&lt;/CombinedTimeout&gt;&lt;!-- Milliseconds --&gt;
        ///  &lt;DebugBreak&gt;on&lt;/DebugBreak&gt;
        ///  &lt;DllFilenameFilter&gt;^CatchDll&lt;/DllFilenameFilter&gt;
        ///  &lt;DllPostfix&gt;_D&lt;/DllPostfix&gt;
        ///  &lt;DllRunner&gt;${dllpath}/CatchDllRunner.exe&lt;/DllRunner&gt;
        ///  &lt;DllRunnerCommandline&gt;${catch2} ${dll}&lt;/DllRunnerCommandline&gt;
        ///  &lt;DiscoverCommandLine&gt;--discover&lt;/DiscoverCommandLine&gt;
        ///  &lt;DiscoverTimeout&gt;2000&lt;/DiscoverTimeout&gt;
        ///  &lt;Environment&gt;
        ///    &lt;PATH&gt;D:\MyPath; D:\MyOtherPath&lt;/PATH&gt;
        ///    &lt;MyCustomEnvSetting value=&quot;deb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlSettingsOverride_ExecutionModeForceSingleTagRgx {
            get {
                return ResourceManager.GetString("XmlSettingsOverride_ExecutionModeForceSingleTagRgx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;CombinedTimeout&gt;30000&lt;/CombinedTimeout&gt;&lt;!-- Milliseconds --&gt;
        ///  &lt;DebugBreak&gt;on&lt;/DebugBreak&gt;
        ///  &lt;DllFilenameFilter&gt;^CatchDll&lt;/DllFilenameFilter&gt;
        ///  &lt;DllPostfix&gt;_D&lt;/DllPostfix&gt;
        ///  &lt;DllRunner&gt;${dllpath}/CatchDllRunner.exe&lt;/DllRunner&gt;
        ///  &lt;DllRunnerCommandline&gt;${catch2} ${dll}&lt;/DllRunnerCommandline&gt;
        ///  &lt;DiscoverCommandLine&gt;--discover&lt;/DiscoverCommandLine&gt;
        ///  &lt;DiscoverTimeout&gt;2000&lt;/DiscoverTimeout&gt;
        ///  &lt;Environment&gt;
        ///    &lt;PATH&gt;D:\MyPath; D:\MyOtherPath&lt;/PATH&gt;
        ///    &lt;MyCustomEnvSetting value=&quot;deb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlSettingsOverride_IncludeHidden {
            get {
                return ResourceManager.GetString("XmlSettingsOverride_IncludeHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;CombinedTimeout&gt;30000&lt;/CombinedTimeout&gt;&lt;!-- Milliseconds --&gt;
        ///  &lt;DebugBreak&gt;on&lt;/DebugBreak&gt;
        ///  &lt;DllFilenameFilter&gt;^CatchDll&lt;/DllFilenameFilter&gt;
        ///  &lt;DllPostfix&gt;_D&lt;/DllPostfix&gt;
        ///  &lt;DllRunner&gt;${dllpath}/CatchDllRunner.exe&lt;/DllRunner&gt;
        ///  &lt;DllRunnerCommandline&gt;${catch2} ${dll}&lt;/DllRunnerCommandline&gt;
        ///  &lt;DiscoverCommandLine&gt;--discover&lt;/DiscoverCommandLine&gt;
        ///  &lt;DiscoverTimeout&gt;2000&lt;/DiscoverTimeout&gt;
        ///  &lt;Environment&gt;
        ///    &lt;PATH&gt;D:\MyPath; D:\MyOtherPath&lt;/PATH&gt;
        ///    &lt;MyCustomEnvSetting value=&quot;deb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlSettingsOverride_LoggingLevel {
            get {
                return ResourceManager.GetString("XmlSettingsOverride_LoggingLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;CombinedTimeout&gt;30000&lt;/CombinedTimeout&gt;&lt;!-- Milliseconds --&gt;
        ///  &lt;DebugBreak&gt;on&lt;/DebugBreak&gt;
        ///  &lt;DllFilenameFilter&gt;^CatchDll&lt;/DllFilenameFilter&gt;
        ///  &lt;DllPostfix&gt;_D&lt;/DllPostfix&gt;
        ///  &lt;DllRunner&gt;${dllpath}/CatchDllRunner.exe&lt;/DllRunner&gt;
        ///  &lt;DllRunnerCommandline&gt;${catch2} ${dll}&lt;/DllRunnerCommandline&gt;
        ///  &lt;DiscoverCommandLine&gt;--discover&lt;/DiscoverCommandLine&gt;
        ///  &lt;DiscoverTimeout&gt;2000&lt;/DiscoverTimeout&gt;
        ///  &lt;Environment&gt;
        ///    &lt;PATH&gt;D:\MyPath; D:\MyOtherPath&lt;/PATH&gt;
        ///    &lt;MyCustomEnvSetting value=&quot;deb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlSettingsOverride_MessageFormat {
            get {
                return ResourceManager.GetString("XmlSettingsOverride_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;CombinedTimeout&gt;30000&lt;/CombinedTimeout&gt;&lt;!-- Milliseconds --&gt;
        ///  &lt;DebugBreak&gt;on&lt;/DebugBreak&gt;
        ///  &lt;DllFilenameFilter&gt;^CatchDll&lt;/DllFilenameFilter&gt;
        ///  &lt;DllPostfix&gt;_D&lt;/DllPostfix&gt;
        ///  &lt;DllRunner&gt;${dllpath}/CatchDllRunner.exe&lt;/DllRunner&gt;
        ///  &lt;DllRunnerCommandline&gt;${catch2} ${dll}&lt;/DllRunnerCommandline&gt;
        ///  &lt;DiscoverCommandLine&gt;--discover&lt;/DiscoverCommandLine&gt;
        ///  &lt;DiscoverTimeout&gt;2000&lt;/DiscoverTimeout&gt;
        ///  &lt;Environment&gt;
        ///    &lt;PATH&gt;D:\MyPath; D:\MyOtherPath&lt;/PATH&gt;
        ///    &lt;MyCustomEnvSetting value=&quot;deb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlSettingsOverride_MultipleOverrides {
            get {
                return ResourceManager.GetString("XmlSettingsOverride_MultipleOverrides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;CombinedTimeout&gt;30000&lt;/CombinedTimeout&gt;&lt;!-- Milliseconds --&gt;
        ///  &lt;DebugBreak&gt;on&lt;/DebugBreak&gt;
        ///  &lt;DllFilenameFilter&gt;^CatchDll&lt;/DllFilenameFilter&gt;
        ///  &lt;DllPostfix&gt;_D&lt;/DllPostfix&gt;
        ///  &lt;DllRunner&gt;${dllpath}/CatchDllRunner.exe&lt;/DllRunner&gt;
        ///  &lt;DllRunnerCommandline&gt;${catch2} ${dll}&lt;/DllRunnerCommandline&gt;
        ///  &lt;DiscoverCommandLine&gt;--discover&lt;/DiscoverCommandLine&gt;
        ///  &lt;DiscoverTimeout&gt;2000&lt;/DiscoverTimeout&gt;
        ///  &lt;Environment&gt;
        ///    &lt;PATH&gt;D:\MyPath; D:\MyOtherPath&lt;/PATH&gt;
        ///    &lt;MyCustomEnvSetting value=&quot;deb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlSettingsOverride_StacktraceFormat {
            get {
                return ResourceManager.GetString("XmlSettingsOverride_StacktraceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;CombinedTimeout&gt;30000&lt;/CombinedTimeout&gt;&lt;!-- Milliseconds --&gt;
        ///  &lt;DebugBreak&gt;on&lt;/DebugBreak&gt;
        ///  &lt;DllFilenameFilter&gt;^CatchDll&lt;/DllFilenameFilter&gt;
        ///  &lt;DllPostfix&gt;_D&lt;/DllPostfix&gt;
        ///  &lt;DllRunner&gt;${dllpath}/CatchDllRunner.exe&lt;/DllRunner&gt;
        ///  &lt;DllRunnerCommandline&gt;${catch2} ${dll}&lt;/DllRunnerCommandline&gt;
        ///  &lt;DiscoverCommandLine&gt;--discover&lt;/DiscoverCommandLine&gt;
        ///  &lt;DiscoverTimeout&gt;2000&lt;/DiscoverTimeout&gt;
        ///  &lt;Environment&gt;
        ///    &lt;PATH&gt;D:\MyPath; D:\MyOtherPath&lt;/PATH&gt;
        ///    &lt;MyCustomEnvSetting value=&quot;deb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlSettingsOverride_StacktraceMaxLength {
            get {
                return ResourceManager.GetString("XmlSettingsOverride_StacktraceMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;CombinedTimeout&gt;30000&lt;/CombinedTimeout&gt;&lt;!-- Milliseconds --&gt;
        ///  &lt;DebugBreak&gt;on&lt;/DebugBreak&gt;
        ///  &lt;DllFilenameFilter&gt;^CatchDll&lt;/DllFilenameFilter&gt;
        ///  &lt;DllPostfix&gt;_D&lt;/DllPostfix&gt;
        ///  &lt;DllRunner&gt;${dllpath}/CatchDllRunner.exe&lt;/DllRunner&gt;
        ///  &lt;DllRunnerCommandline&gt;${catch2} ${dll}&lt;/DllRunnerCommandline&gt;
        ///  &lt;DiscoverCommandLine&gt;--discover&lt;/DiscoverCommandLine&gt;
        ///  &lt;DiscoverTimeout&gt;2000&lt;/DiscoverTimeout&gt;
        ///  &lt;Environment&gt;
        ///    &lt;PATH&gt;D:\MyPath; D:\MyOtherPath&lt;/PATH&gt;
        ///    &lt;MyCustomEnvSetting value=&quot;deb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlSettingsOverride_StacktracePointReplacement {
            get {
                return ResourceManager.GetString("XmlSettingsOverride_StacktracePointReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Catch2Adapter&gt;
        ///  &lt;CombinedTimeout&gt;30000&lt;/CombinedTimeout&gt;&lt;!-- Milliseconds --&gt;
        ///  &lt;DebugBreak&gt;on&lt;/DebugBreak&gt;
        ///  &lt;DllFilenameFilter&gt;^CatchDll&lt;/DllFilenameFilter&gt;
        ///  &lt;DllPostfix&gt;_D&lt;/DllPostfix&gt;
        ///  &lt;DllRunner&gt;${dllpath}/CatchDllRunner.exe&lt;/DllRunner&gt;
        ///  &lt;DllRunnerCommandline&gt;${catch2} ${dll}&lt;/DllRunnerCommandline&gt;
        ///  &lt;DiscoverCommandLine&gt;--discover&lt;/DiscoverCommandLine&gt;
        ///  &lt;DiscoverTimeout&gt;2000&lt;/DiscoverTimeout&gt;
        ///  &lt;Environment&gt;
        ///    &lt;PATH&gt;D:\MyPath; D:\MyOtherPath&lt;/PATH&gt;
        ///    &lt;MyCustomEnvSetting value=&quot;deb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlSettingsOverride_TestCaseTimeout {
            get {
                return ResourceManager.GetString("XmlSettingsOverride_TestCaseTimeout", resourceCulture);
            }
        }
    }
}
